require 'MrMurano/commands/account'
require 'MrMurano/commands/assign'
require 'MrMurano/commands/config'
require 'MrMurano/commands/content'
require 'MrMurano/commands/cors'
require 'MrMurano/commands/domain'
require 'MrMurano/commands/exportImport'
require 'MrMurano/commands/keystore'
require 'MrMurano/commands/logs'
require 'MrMurano/commands/productCreate'
require 'MrMurano/commands/productDelete'
require 'MrMurano/commands/productList'
require 'MrMurano/commands/productSpec'
require 'MrMurano/commands/productWrite'
require 'MrMurano/commands/serialNumberCmds'
require 'MrMurano/commands/solutionCreate'
require 'MrMurano/commands/solutionDelete'
require 'MrMurano/commands/solutionList'
require 'MrMurano/commands/status'
require 'MrMurano/commands/sync'
require 'MrMurano/commands/timeseries'

require 'MrMurano/commands/completion'

