require 'MrMurano/commands/assign'
require 'MrMurano/commands/businessList'
#require 'MrMurano/commands/completion'
require 'MrMurano/commands/config'
require 'MrMurano/commands/content'
require 'MrMurano/commands/cors'
require 'MrMurano/commands/devices'
require 'MrMurano/commands/domain'
require 'MrMurano/commands/init'
require 'MrMurano/commands/keystore'
require 'MrMurano/commands/logs'
require 'MrMurano/commands/mock'
require 'MrMurano/commands/postgresql'
require 'MrMurano/commands/password'
require 'MrMurano/commands/project'
require 'MrMurano/commands/projectCreate'
require 'MrMurano/commands/projectDelete'
require 'MrMurano/commands/projectList'
require 'MrMurano/commands/show'
require 'MrMurano/commands/status'
require 'MrMurano/commands/sync'
require 'MrMurano/commands/timeseries'
require 'MrMurano/commands/tsdb'
require 'MrMurano/commands/usage'


